package app.utils;

public enum APIResponse {
	INVALID_INPUT("INVALID_INPUT"),
	INVALID_CALLER("INVALID_CALLER"),
	MISSING_INPUT("MISSING_INPUT"),
	SUCCESS("SUCCESS"),
	CONTENTQPA_ERROR("CONTENTQPA_ERROR"),
	INTERNAL_ERROR("INTERNAL_ERROR"),
	MONGODB_ERROR("MONGODB_ERROR"),
	NOT_LOGIN("NOT_LOGIN"),
	PROFILE_NOT_FOUND("PROFILE_NOT_FOUND"),
	DUPLICATE_PROFILE_FOUND("DUPLICATE_PROFILE_FOUND"),
	PROFILE_NOT_MATCH("PROFILE_NOT_MATCH"),
	RECOMMENDATION_ENGINE_ERROR("RECOMMENDATION_ENGINE_ERROR"),
	PVR_API_ERROR("PVR_API_ERROR"),
	PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
	NEED_SUB("NEED_SUB"),
	U3API_ERROR("U3API_ERROR"),
	DATABASE_EXECUTION_ERROR("DATABASE_EXECUTION_ERROR"),
	API_NOT_FOUND("API_NOT_FOUND"),
	INVALID_USER_SESSION("INVALID_USER_SESSION"),
	INVALID_PIN("INVALID_PIN"),
	INVALID_TOKEN("INVALID_TOKEN"),
	UPS_ERROR("UPS_ERROR"),
	INVALID_PID("INVALID_PID"),
	JOB_EXECUTED("JOB_EXECUTED")
	;
	
	private String responseCode;

	APIResponse(String responseCode) {
		this.responseCode=responseCode;
	}
	
	public String getResponseCode(){
		return this.responseCode;
	}
}
